# Generated by Django 4.0.4 on 2022-05-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fase',
        ),
        migrations.AddField(
            model_name='post',
            name='phase',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='maturationTime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
