# Generated by Django 4.1.1 on 2022-10-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_value', models.IntegerField()),
                ('user', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=256)),
                ('course', models.CharField(max_length=256)),
                ('transfer_user', models.CharField(max_length=7)),
                ('transfer_name', models.CharField(max_length=256)),
                ('transfer_course', models.CharField(max_length=256)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=256)),
                ('course', models.CharField(max_length=256)),
                ('image', models.URLField(blank=True, max_length=256, null=True)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
    ]
