# Generated by Django 4.1.1 on 2022-09-11 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('enrollment', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('course', models.CharField(max_length=256)),
                ('image', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transfer_value', models.IntegerField()),
                ('transfer_user', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wallet')),
            ],
        ),
        migrations.AddField(
            model_name='wallet',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.users'),
            preserve_default=False,
        ),
    ]
